### ISSUE TITLE
php unit testing

### ISSUE THREAD

**Issue by murraycollingwood** [pontedilana/php-weasyprint#8]
Hello

I'm trying to implement some php unit testing around my PDF generation.
I can easily check the creation of the PDF document, but if I want to ensure it contains the text I'm looking for, formatted in a similar manner, I'm having trouble.

I found this article (https://stackoverflow.com/questions/32489513/software-testing-a-pdf-is-created-correctly) which suggested generating the PDF and comparing it to a previously generated PDF, which I tried, but it didn't work.  Even though both contained exactly the same content the strings were never the same.

Do you have any suggestions how I might be able to ensure my PDF contains the correct content?

**Comment by endelwar** [comment]
Hi!
Reproducible PDF as been introduced in [WeasyPrint 55.0b1](https://github.com/Kozea/WeasyPrint/releases/tag/v55.0b1) and fixed in 56.0 (see https://github.com/Kozea/WeasyPrint/issues/1666).

in a comment to [issue #1553](https://github.com/Kozea/WeasyPrint/issues/1553#issuecomment-1023269745) is suggested to add a meta tag to html:

```html
<meta name="dcterms.created" content="2023-05-10">
```

Keeping the `content` fixed and setting a system ENV to a fixed value (`SOURCE_DATE_EPOCH=0`) should be enough to create reproducible pdf.

Let me know if this solves your problem!

**Comment by endelwar** [comment]
Was your problem solved with my suggestions?
